import { lawEntries } from "./shared-law-fines.mjs";

const lawTexts = {
  speeding: { title: "अधिवेग", desc: "राजमार्ग, शहरी सड़क या स्कूल क्षेत्रों में निर्धारित गति सीमा से अधिक गति से चलना।" },
  dangerous: { title: "खतरनाक ड्राइविंग", desc: "ऐसे तरीके से चलाना जो दूसरों के जीवन या संपत्ति को खतरे में डाले।" },
  dui: { title: "नशे में ड्राइविंग", desc: "रक्त में 30mg/100ml से अधिक शराब के साथ चलाना।" },
  seatbelt: { title: "सीटबेल्ट उल्लंघन", desc: "गाड़ी चलते समय ड्राइवर या आगे की सीट पर सीटबेल्ट न पहनना।" },
  helmet: { title: "हेलमेट न पहनना", desc: "दोपहिया वाहन पर ISI प्रमाणित हेलमेट न पहनना।" },
  redLight: { title: "लाल बत्ती कूदना", desc: "स्टॉप लाइन पर रुके बिना लाल सिग्नल पार करना।" },
  mobile: { title: "ड्राइविंग में मोबाइल", desc: "चलाते समय हाथ में मोबाइल का उपयोग।" },
  wrongSide: { title: "गलत तरफ चलना", desc: "सड़क की गलत दिशा या वन-वे पर विपरीत दिशा में चलना।" },
  overloading: { title: "ओवरलोडिंग", desc: "पंजीकृत क्षमता से अधिक यात्री या माल ढोना।" },
  insurance: { title: "बीमा के बिना चलाना", desc: "वैध थर्ड-पार्टी बीमा के बिना सार्वजनिक सड़क पर वाहन चलाना।" },
  licence: { title: "लाइसेंस के बिना चलाना", desc: "वैध ड्राइविंग लाइसेंस के बिना वाहन चलाना।" },
  racing: { title: "अनधिकृत रेसिंग", desc: "लिखित सरकारी अनुमति के बिना सार्वजनिक सड़क पर गति प्रतियोगिता।" },
};

/** Hindi page-section overrides (merged into locale JSON). */
export default {
  dashboardLive: {
    subtitlePrefix: "लाइव सड़क सुरक्षा विश्लेषण",
    activeIncidents: "सक्रिय घटनाएं",
    sinceYesterday: "कल से 3 अधिक",
    issuesReported: "रिपोर्ट की गई समस्याएं",
    today: "आज 12",
    sosActivations: "SOS सक्रियण",
    thisMonth: "इस महीने",
    resolvedIssues: "हल की गई समस्याएं",
    resolutionRate: "समाधान दर",
    accidentHotspots: "दुर्घटना हॉटस्पॉट",
    topZones: "शीर्ष 5 क्षेत्र · पिछले 30 दिन",
    live: "लाइव",
    recentReports: "हाल की रिपोर्ट",
    liveMapView: "लाइव मानचित्र",
    connectMaps: "सक्षम करने के लिए Google Maps API जोड़ें",
    severity: { critical: "गंभीर", high: "उच्च", medium: "मध्यम", low: "कम" },
    status: { pending: "लंबित", verified: "सत्यापित", inProgress: "प्रगति में", resolved: "हल" },
    issueTypes: { pothole: "गड्ढा", waterlogging: "जलभराव", damagedRoad: "क्षतिग्रस्त सड़क", brokenDivider: "टूटा डिवाइडर", missingSign: "गायब संकेत" },
  },
  reportIssuePage: {
    title: "समस्या रिपोर्ट करें",
    subtitle: "AI पहचान के लिए सड़क की तस्वीर अपलोड करें",
    uploadTitle: "सड़क की तस्वीर अपलोड करें",
    uploadSubtitle: "AI पहचान शुरू करने के लिए तस्वीर डालें या डिवाइस से चुनें.",
    issueType: "समस्या प्रकार",
    severity: "गंभीरता",
    roadLocation: "सड़क / स्थान *",
    roadPlaceholder: "जैसे NH-48, KM 14 महिपालपुर फ्लाईओवर के पास",
    area: "क्षेत्र / इलाका",
    areaPlaceholder: "जैसे दक्षिण दिल्ली",
    notes: "अतिरिक्त नोट्स",
    notesPlaceholder: "समस्या, अवधि और खतरे का स्तर लिखें...",
    submit: "रिपोर्ट जमा करें",
    submittedTitle: "रिपोर्ट जमा हुई",
    submittedMessage: "आपकी सड़क समस्या दर्ज हो गई है और हमारी टीम सत्यापित करेगी. भारतीय सड़कों को सुरक्षित बनाने में मदद के लिए धन्यवाद.",
    reportAnother: "दूसरी रिपोर्ट करें",
    viewDashboard: "डैशबोर्ड देखें",
    issueTypes: { pothole: "गड्ढा", damage: "क्षतिग्रस्त सड़क", water: "जलभराव", divider: "टूटा डिवाइडर", sign: "गायब संकेत", other: "अन्य" },
    severityLevels: { critical: "गंभीर", high: "उच्च", medium: "मध्यम", low: "कम" },
    simulated: { pothole: "गहरा गड्ढा उच्च भरोसे के साथ मिला. तुरंत मरम्मत की सलाह.", damage: "सड़क सतह में दरार और धंसाव मिला.", water: "सड़क पर खड़ा पानी मिला. अनुमानित गहराई 10cm से अधिक.", surface: "सामान्य सड़क सतह घिसाव मिला. रखरखाव आवश्यक है." },
  },
  uploader: { invalidImage: "कृपया मान्य छवि फ़ाइल चुनें.", selected: "चुना गया: {{fileName}}", supportedFormats: "JPG, PNG, WEBP और सामान्य छवि प्रारूप समर्थित हैं.", previewAlt: "सड़क समस्या पूर्वावलोकन", dropHere: "अपनी तस्वीर यहां डालें", chooseHint: "या डिवाइस से फ़ाइल चुनें", chooseImage: "तस्वीर चुनें" },
  detector: { analyzingTitle: "छवि विश्लेषण", analyzingDescription: "AI पाइपलाइन सड़क क्षति पैटर्न जांच रही है.", running: "पहचान चल रही है...", failedTitle: "पहचान विफल", emptyTitle: "अभी कोई पहचान नहीं", emptyDescription: "AI आधारित आकलन के लिए तस्वीर अपलोड करें.", resultTitle: "AI पहचान परिणाम", fallbackLabel: "सड़क समस्या मिली", severityLabel: "{{severity}} गंभीरता", fallbackDescription: "छवि का विश्लेषण कर वर्तमान मॉडल से वर्गीकृत किया गया है.", confidence: "भरोसा", fallbackType: "सड़क क्षति वर्गीकरण", uploadedPreview: "अपलोड पूर्वावलोकन", uploadedAlt: "अपलोड की गई सड़क समस्या" },
  sosPage: {
    title: "आपातकालीन SOS", subtitle: "लाइव स्थान के साथ एक-टैप आपात अलर्ट", buttonSub: "आपातकाल", ready: "सिस्टम तैयार · GPS सक्रिय", locating: "स्थान प्राप्त हो रहा है...", dispatched: "अलर्ट भेजा गया · सेवाएं सूचित", alertSent: "अलर्ट भेजा गया", servicesEta: "सेवाएं सूचित · ETA ~6 मिनट", reset: "रीसेट", helper: "अपना स्थान तुरंत आपात सेवाओं और संपर्कों को भेजने के लिए SOS दबाएं.", numbers: "आपात नंबर", whatNext: "आगे क्या होगा",
    contacts: { police: "पुलिस", ambulance: "एम्बुलेंस", fire: "अग्निशमन", road: "सड़क हेल्पलाइन" },
    steps: { capture: "आपके GPS निर्देशांक कैप्चर कर बैकएंड को भेजे जाते हैं.", hospitals: "नजदीकी अस्पताल और आपात इकाइयां पहचानी जाती हैं.", ambulance: "अनुमानित समय के साथ एम्बुलेंस भेजी जाती है.", sms: "आपके आपात संपर्कों को SMS से स्थान मिलता है." },
  },
  riskPage: {
    title: "जोखिम अलर्ट", subtitle: "आपके मार्ग के लिए ML आधारित दुर्घटना जोखिम अनुमान", predictor: "जोखिम अनुमानक", predictorHelp: "स्थितियां सेट करें. मॉडल जोखिम स्कोर लौटाता है.", select: "चुनें...", analyze: "जोखिम विश्लेषण चलाएं", analyzing: "विश्लेषण...", riskFactors: "जोखिम कारक", currentScore: "वर्तमान जोन जोखिम स्कोर", feed: "लाइव अलर्ट फ़ीड", scoreSuffix: "/100",
    labels: { critical: "गंभीर", highRisk: "उच्च जोखिम", moderate: "मध्यम", lowRisk: "कम जोखिम" },
    advice: { critical: "संभव हो तो इस क्षेत्र से बचें. दुर्घटना संभावना अधिक है.", high: "बहुत सावधानी से चलाएं. कई जोखिम कारक सक्रिय हैं.", medium: "सामान्य सावधानी रखें. स्थितियों पर नजर रखें.", low: "क्षेत्र सुरक्षित दिखता है. सामान्य सावधानी रखें." },
    conditions: { time: "समय", weather: "मौसम", road: "सड़क स्थिति", traffic: "यातायात स्तर" },
    options: { peakMorning: "सुबह चरम (7-10)", afternoon: "दोपहर", peakEvening: "शाम चरम (5-9)", lateNight: "देर रात", earlyMorning: "सुबह जल्दी", clear: "साफ", lightRain: "हल्की बारिश", heavyRain: "भारी बारिश", fog: "कोहरा", denseFog: "घना कोहरा", extremeHeat: "अत्यधिक गर्मी", good: "अच्छी", minorDamage: "हल्की क्षति", potholes: "गड्ढे", waterlogged: "जलभराव", construction: "निर्माण क्षेत्र", severelyDamaged: "गंभीर क्षति", low: "कम", moderate: "मध्यम", heavy: "भारी", stopGo: "रुक-चल", accidentInduced: "दुर्घटना से" },
    alerts: { wetRoad: "चरम घंटा + गीली सड़क", poorVisibility: "रात + कम दृश्यता", construction: "निर्माण क्षेत्र सक्रिय", traffic: "मध्यम यातायात", slick: "हल्की बारिश, फिसलन", visibility: "दृश्यता थोड़ी कम", now: "अभी", minAgo: "{{count}} मिनट पहले" },
  },
  legalPage: {
    title: "कानूनी जानकारी", subtitle: "भारतीय मोटर वाहन अधिनियम 2019 के यातायात कानून और जुर्माने", prototypeTitle: "प्रोटोटाइप मॉड्यूल", prototype: "यह स्थिर संदर्भ है. आधिकारिक स्रोतों से सत्यापित करें.", searchPlaceholder: "कानून, धारा, टैग खोजें...", category: "श्रेणी", quickFacts: "त्वरित तथ्य", futureScope: "भविष्य का दायरा", futureScopeText: "GPS के आधार पर राज्य और शहर-विशिष्ट नियम दिखाए जाएंगे.", showing: "दिखा रहे हैं", ofRules: "{{count}} नियमों में से", clearSearch: "खोज साफ करें", noMatch: "आपकी खोज से कोई कानून नहीं मिला", firstOffence: "पहला अपराध", repeatOffence: "दोहराया अपराध", imprisonment: "कारावास: {{term}}",
    categories: { all: "सभी", speed: "गति", safety: "सुरक्षा", signals: "संकेत", driving: "ड्राइविंग", mobile: "मोबाइल", lane: "लेन", overloading: "ओवरलोडिंग", insurance: "बीमा", documents: "दस्तावेज", impairment: "नशा" },
    facts: { maxFine: "अधिकतम जुर्माना", drunkMax: "नशे में ड्राइविंग अधिकतम", listed: "सूचीबद्ध अपराध", actVersion: "अधिनियम संस्करण" },
    factsValues: { maxFine: "₹20,000", drunkMax: "₹15,000+", listed: "{{count}} कानून", actVersion: "MV Act 2019" },
    lawEntries: lawEntries(lawTexts),
  },
  sosModal: {
    ariaLabel: "आपात SOS अलर्ट", badge: "SOS", close: "बंद करें", seconds: "सेकंड", confirmIntro: "आपात SOS अलर्ट आपके ", liveLocation: "लाइव स्थान", confirmMiddle: " के साथ आपात सेवाओं और ", emergencyContacts: "आपात संपर्कों", confirmEnd: " को भेजा जाएगा.", cancel: "रद्द करें", sendNow: "अभी भेजें",
    stages: { confirm: "आपात अलर्ट", locating: "आपका स्थान खोज रहे हैं…", sending: "भेज रहे हैं…", sent: "अलर्ट भेजा गया" },
    acquiringGps: "GPS सिग्नल प्राप्त हो रहा है", keepOpen: "कृपया ऐप खुला रखें…", searchingSatellites: "उपग्रह खोज रहे हैं", contactingServices: "आपात सेवाओं से संपर्क", notifyingUnits: "नजदीकी इकाइयों और संपर्कों को सूचित कर रहे हैं…", alertSent: "अलर्ट भेजा गया", servicesNotified: "आपात सेवाओं को सूचित कर दिया गया है", geoNotSupported: "जियोलोकेशन समर्थित नहीं — डिफ़ॉल्ट स्थान उपयोग.", geoFailed: "GPS नहीं मिला — अनुमानित स्थान उपयोग.", defaultLocation: "नई दिल्ली (डिफ़ॉल्ट)", approxLocation: "नई दिल्ली (अनुमानित)", ambulanceEta: "एम्बुलेंस ETA", unitDispatched: "यूनिट भेजी गई — लाइव ट्रैकिंग", nearbyHospitals: "नजदीकी अस्पताल", away: "दूर", done: "पूर्ण", callHospital: "{{name}} को कॉल करें",
  },
  mapUi: { yourLocation: "आपका स्थान", noApiKey: "Google Maps API कुंजी नहीं मिली.", loadFailed: "Google Maps लोड विफल.", initialising: "मानचित्र शुरू हो रहा है…", zoomIn: "ज़ूम इन", zoomOut: "ज़ूम आउट", recenter: "मानचित्र केंद्रित करें", hospitals: "अस्पताल", incidents: "घटनाएं", heatmap: "हीटमैप", satellite: "उपग्रह", map: "मानचित्र", you: "आप", reportedIssues: "रिपोर्ट की गई समस्याएं", searchPlaceholder: "सड़क, क्षेत्र, प्रकार खोजें…", all: "सभी", hotspotsTitle: "दुर्घटना हॉटस्पॉट", hotspotsSubtitle: "पिछले 30 दिन · स्वतः अपडेट", totalIncidents: "कुल घटनाएं", peakHour: "चरम घंटा", trending: "बढ़ रहा ↑", total24h: "कुल / 24 घंटे" },
  locationErrors: { denied: "स्थान पहुंच अस्वीकृत. ब्राउज़र में GPS सक्षम करें.", unavailable: "स्थान उपलब्ध नहीं. GPS सिग्नल जांचें.", timeout: "स्थान अनुरोध समय समाप्त. पुनः प्रयास करें.", unknown: "अज्ञात स्थान त्रुटि हुई." },
  sos: { title: "आपातकालीन SOS", description: "आपातकाल में तुरंत मदद प्राप्त करें", buttonLabel: "आपातकाल के लिए दबाएं", nearbyHospitals: "पास के अस्पताल", emergencyServices: "आपातकालीन सेवाएं", contactingServices: "आपातकालीन सेवाओं से संपर्क...", locationSharing: "आपका स्थान साझा किया जा रहा है" },
  map: { title: "मानचित्र दृश्य", noData: "प्रदर्शित करने के लिए कोई घटनाएं नहीं", zoomToFit: "फिट करने के लिए ज़ूम", currentLocation: "वर्तमान स्थान" },
};
