import { lawEntries } from "./shared-law-fines.mjs";

const lawTexts = {
  speeding: { title: "ಅತಿವೇಗ", desc: "ಹೆದ್ದಾರಿ, ನಗರ ಅಥವಾ ಶಾಲಾ ಪ್ರದೇಶಗಳಲ್ಲಿ ನಿಗದಿತ ವೇಗ ಮೀರಿ ಚಾಲನೆ." },
  dangerous: { title: "ಅಪಾಯಕಾರಿ ಚಾಲನೆ", desc: "ಇತರರ ಜೀವ ಅಥವಾ ಆಸ್ತಿಗೆ ಅಪಾಯ ಉಂಟುಮಾಡುವ ರೀತಿಯಲ್ಲಿ ಚಾಲನೆ." },
  dui: { title: "ಮದ್ಯಪಾನ ಚಾಲನೆ", desc: "ರಕ್ತದಲ್ಲಿ 30mg/100ml ಗಿಂತ ಹೆಚ್ಚು ಆಲ್ಕೋಹಾಲ್ ಜೊತೆ ಚಾಲನೆ." },
  seatbelt: { title: "ಸೀಟ್ ಬೆಲ್ಟ್ ಉಲ್ಲಂಘನೆ", desc: "ವಾಹನ ಚಲಿಸುತ್ತಿರುವಾಗ ಸೀಟ್ ಬೆಲ್ಟ್ ಧರಿಸದಿರುವುದು." },
  helmet: { title: "ಹೆಲ್ಮೆಟ್ ಧರಿಸದಿರುವುದು", desc: "ಎರಡು ಚಕ್ರ ವಾಹನದಲ್ಲಿ ISI ಹೆಲ್ಮೆಟ್ ಧರಿಸದಿರುವುದು." },
  redLight: { title: "ಕೆಂಪು ಬೆಳಕು ಮೀರಿಸುವುದು", desc: "ಸ್ಟಾಪ್ ಲೈನ್ ನಲ್ಲಿ ನಿಲ್ಲದೆ ಕೆಂಪು ಸಿಗ್ನಲ್ ದಾಟುವುದು." },
  mobile: { title: "ಚಾಲನೆಯಲ್ಲಿ ಮೊಬೈಲ್", desc: "ಚಾಲನೆ ಮಾಡುತ್ತಿರುವಾಗ ಕೈಯಲ್ಲಿ ಮೊಬೈಲ್ ಬಳಕೆ." },
  wrongSide: { title: "ತಪ್ಪು ಬದಿ ಚಾಲನೆ", desc: "ರಸ್ತೆಯ ತಪ್ಪು ಬದಿ ಅಥವಾ ಒನ್-ವೇ ನಲ್ಲಿ ವಿರುದ್ಧ ದಿಶೆಯಲ್ಲಿ ಚಾಲನೆ." },
  overloading: { title: "ಓವರ್ ಲೋಡಿಂಗ್", desc: "ನೋಂದಾಯಿತ ಸಾಮರ್ಥ್ಯ ಮೀರಿ ಪ್ರಯಾಣಿಕರು ಅಥವಾ ಸರಕು." },
  insurance: { title: "ವಿಮೆ ಇಲ್ಲದೆ ಚಾಲನೆ", desc: "ಮಾನ್ಯ ಥರ್ಡ್-ಪಾರ್ಟಿ ವಿಮೆ ಇಲ್ಲದೆ ಸಾರ್ವಜನಿಕ ರಸ್ತೆಯಲ್ಲಿ ಚಾಲನೆ." },
  licence: { title: "ಲೈಸೆನ್ಸ್ ಇಲ್ಲದೆ", desc: "ಮಾನ್ಯ ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್ ಇಲ್ಲದೆ ವಾಹನ ಚಾಲನೆ." },
  racing: { title: "ಅನಧಿಕೃತ ರೇಸಿಂಗ್", desc: "ಸರ್ಕಾರಿ ಅನುಮತಿ ಇಲ್ಲದೆ ಸಾರ್ವಜನಿಕ ರಸ್ತೆಯಲ್ಲಿ ವೇಗ ಸ್ಪರ್ಧೆ." },
};

export default {
  dashboardLive: {
    subtitlePrefix: "ಲೈವ್ ರಸ್ತೆ ಸುರಕ್ಷತಾ ವಿಶ್ಲೇಷಣೆ",
    activeIncidents: "ಸಕ್ರಿಯ ಘಟನೆಗಳು",
    sinceYesterday: "ನಿನ್ನೆಯಿಂದ 3 ಹೆಚ್ಚು",
    issuesReported: "ವರದಿಯಾದ ಸಮಸ್ಯೆಗಳು",
    today: "ಇಂದು 12",
    sosActivations: "SOS ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆಗಳು",
    thisMonth: "ಈ ತಿಂಗಳು",
    resolvedIssues: "ಪರಿಹರಿಸಿದ ಸಮಸ್ಯೆಗಳು",
    resolutionRate: "ಪರಿಹಾರ ದರ",
    accidentHotspots: "ಅಪಘಾತ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು",
    topZones: "ಟಾಪ್ 5 ವಲಯಗಳು · ಕಳೆದ 30 ದಿನಗಳು",
    live: "ಲೈವ್",
    recentReports: "ಇತ್ತೀಚಿನ ವರದಿಗಳು",
    liveMapView: "ಲೈವ್ ನಕ್ಷೆ",
    connectMaps: "Google Maps API ಸಂಪರ್ಕಿಸಿ",
    severity: { critical: "ಗಂಭೀರ", high: "ಹೆಚ್ಚು", medium: "ಮಧ್ಯಮ", low: "ಕಡಿಮೆ" },
    status: { pending: "ಬಾಕಿ", verified: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ", inProgress: "ಪ್ರಗತಿಯಲ್ಲಿದೆ", resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ" },
    issueTypes: { pothole: "ಗುಂಡಿ", waterlogging: "ನೀರು ನಿಂತಿದೆ", damagedRoad: "ಹಾನಿಗೊಳಗಾದ ರಸ್ತೆ", brokenDivider: "ಮುರಿದ ಡಿವೈಡರ್", missingSign: "ಕಾಣೆಯಾದ ಚಿಹ್ನೆ" },
  },
  reportIssuePage: {
    title: "ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ",
    subtitle: "AI ಪತ್ತೆಗಾಗಿ ರಸ್ತೆ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    uploadTitle: "ರಸ್ತೆ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್",
    uploadSubtitle: "AI ಪತ್ತೆ ಪ್ರಾರಂಭಿಸಲು ಚಿತ್ರವನ್ನು ಡ್ರಾಪ್ ಮಾಡಿ ಅಥವಾ ಆಯ್ಕೆ ಮಾಡಿ.",
    issueType: "ಸಮಸ್ಯೆ ಪ್ರಕಾರ",
    severity: "ತೀವ್ರತೆ",
    roadLocation: "ರಸ್ತೆ / ಸ್ಥಳ *",
    roadPlaceholder: "ಉದಾ. NH-48, KM 14 ಮಹಿಪಾಲ್ಪುರ್ ಬಳಿ",
    area: "ಪ್ರದೇಶ",
    areaPlaceholder: "ಉದಾ. ದಕ್ಷಿಣ ದೆಹಲಿ",
    notes: "ಹೆಚ್ಚುವರಿ ಟಿಪ್ಪಣಿಗಳು",
    notesPlaceholder: "ಸಮಸ್ಯೆ, ಅವಧಿ, ಅಪಾಯ ವಿವರಿಸಿ...",
    submit: "ವರದಿ ಸಲ್ಲಿಸಿ",
    submittedTitle: "ವರದಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    submittedMessage: "ನಿಮ್ಮ ರಸ್ತೆ ಸಮಸ್ಯೆ ದಾಖಲಾಗಿದೆ. ಭಾರತೀಯ ರಸ್ತೆಗಳನ್ನು ಸುರಕ್ಷಿತಗೊಳಿಸಲು ಸಹಾಯಕ್ಕೆ ಧನ್ಯವಾದಗಳು.",
    reportAnother: "ಮತ್ತೊಂದು ವರದಿ",
    viewDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ನೋಡಿ",
    issueTypes: { pothole: "ಗುಂಡಿ", damage: "ಹಾನಿಗೊಳಗಾದ ರಸ್ತೆ", water: "ನೀರು ನಿಂತಿದೆ", divider: "ಮುರಿದ ಡಿವೈಡರ್", sign: "ಕಾಣೆಯಾದ ಚಿಹ್ನೆ", other: "ಇತರೆ" },
    severityLevels: { critical: "ಗಂಭೀರ", high: "ಹೆಚ್ಚು", medium: "ಮಧ್ಯಮ", low: "ಕಡಿಮೆ" },
    simulated: { pothole: "ಆಳವಾದ ಗುಂಡಿ ಹೆಚ್ಚು ವಿಶ್ವಾಸದಿಂದ ಪತ್ತೆಯಾಗಿದೆ.", damage: "ರಸ್ತೆ ಬಿರುಕುಗಳು ಪತ್ತೆಯಾಗಿವೆ.", water: "ರಸ್ತೆಯ ಮೇಲೆ ನಿಂತ ನೀರು ಪತ್ತೆಯಾಗಿದೆ.", surface: "ಸಾಮಾನ್ಯ ರಸ್ತೆ ಧರಣೆ. ನಿರ್ವಹಣೆ ಅಗತ್ಯ." },
  },
  uploader: { invalidImage: "ಮಾನ್ಯ ಚಿತ್ರ ಫೈಲ್ ಆಯ್ಕೆ ಮಾಡಿ.", selected: "ಆಯ್ಕೆ: {{fileName}}", supportedFormats: "JPG, PNG, WEBP ಮತ್ತು ಸಾಮಾನ್ಯ ಫಾರ್ಮ್ಯಾಟ್‌ಗಳು.", previewAlt: "ರಸ್ತೆ ಸಮಸ್ಯೆ ಪೂರ್ವಾವಲೋಕನ", dropHere: "ನಿಮ್ಮ ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಬಿಡಿ", chooseHint: "ಅಥವಾ ಸಾಧನದಿಂದ ಆಯ್ಕೆ ಮಾಡಿ", chooseImage: "ಚಿತ್ರ ಆಯ್ಕೆ" },
  detector: { analyzingTitle: "ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ", analyzingDescription: "AI ರಸ್ತೆ ಹಾನಿ ಮಾದರಿಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತಿದೆ.", running: "ಪತ್ತೆ ನಡೆಯುತ್ತಿದೆ...", failedTitle: "ಪತ್ತೆ ವಿಫಲ", emptyTitle: "ಇನ್ನೂ ಪತ್ತೆ ಇಲ್ಲ", emptyDescription: "AI ಮೌಲ್ಯಮಾಪನಕ್ಕಾಗಿ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.", resultTitle: "AI ಪತ್ತೆ ಫಲಿತಾಂಶ", fallbackLabel: "ರಸ್ತೆ ಸಮಸ್ಯೆ ಪತ್ತೆಯಾಗಿದೆ", severityLabel: "{{severity}} ತೀವ್ರತೆ", fallbackDescription: "ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಿ ವರ್ಗೀಕರಿಸಲಾಗಿದೆ.", confidence: "ವಿಶ್ವಾಸ", fallbackType: "ರಸ್ತೆ ಹಾನಿ ವರ್ಗೀಕರಣ", uploadedPreview: "ಅಪ್‌ಲೋಡ್ ಪೂರ್ವಾವಲೋಕನ", uploadedAlt: "ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ರಸ್ತೆ ಸಮಸ್ಯೆ" },
  sosPage: {
    title: "ತುರ್ತು SOS", subtitle: "ಲೈವ್ ಸ್ಥಳದೊಂದಿಗೆ ಒಂದು ಟ್ಯಾಪ್ ಎಚ್ಚರಿಕೆ", buttonSub: "ತುರ್ತು", ready: "ವ್ಯವಸ್ಥೆ ಸಿದ್ಧ · GPS ಸಕ್ರಿಯ", locating: "ಸ್ಥಳ ಪಡೆಯಲಾಗುತ್ತಿದೆ...", dispatched: "ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗಿದೆ", alertSent: "ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗಿದೆ", servicesEta: "ಸೇವೆಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ · ETA ~6 ನಿಮಿ", reset: "ಮರುಹೊಂದಿಸಿ", helper: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಕಳುಹಿಸಲು SOS ಒತ್ತಿ.", numbers: "ತುರ್ತು ಸಂಖ್ಯೆಗಳು", whatNext: "ಮುಂದೆ ಏನು ಸಂಭವಿಸುತ್ತದೆ",
    contacts: { police: "ಪೊಲೀಸ್", ambulance: "ಆಂಬ್ಯುಲೆನ್ಸ್", fire: "ಅಗ್ನಿಶಾಮಕ", road: "ರಸ್ತೆ ಸಹಾಯವಾಣಿ" },
    steps: { capture: "ನಿಮ್ಮ GPS ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಹಿಡಿಯಲಾಗುತ್ತದೆ.", hospitals: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು ಗುರುತಿಸಲಾಗುತ್ತವೆ.", ambulance: "ಆಂಬ್ಯುಲೆನ್ಸ್ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.", sms: "ತುರ್ತು ಸಂಪರ್ಕಗಳಿಗೆ SMS ಕಳುಹಿಸಲಾಗುತ್ತದೆ." },
  },
  riskPage: {
    title: "ಅಪಾಯ ಎಚ್ಚರಿಕೆಗಳು", subtitle: "ನಿಮ್ಮ ಮಾರ್ಗಕ್ಕೆ ML ಅಪಘಾತ ಅಪಾಯ ಅಂದಾಜು", predictor: "ಅಪಾಯ ಭವಿಷ್ಯವಾಣಿ", predictorHelp: "ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಹೊಂದಿಸಿ. ಮಾದರಿ ಸ್ಕೋರ್ ನೀಡುತ್ತದೆ.", select: "ಆಯ್ಕೆ...", analyze: "ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ", analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...", riskFactors: "ಅಪಾಯ ಅಂಶಗಳು", currentScore: "ಪ್ರಸ್ತುತ ವಲಯ ಅಪಾಯ ಸ್ಕೋರ್", feed: "ಲೈವ್ ಎಚ್ಚರಿಕೆ ಫೀಡ್", scoreSuffix: "/100",
    labels: { critical: "ಗಂಭೀರ", highRisk: "ಹೆಚ್ಚಿನ ಅಪಾಯ", moderate: "ಮಧ್ಯಮ", lowRisk: "ಕಡಿಮೆ ಅಪಾಯ" },
    advice: { critical: "ಸಾಧ್ಯವಾದರೆ ಈ ವಲಯವನ್ನು ತಪ್ಪಿಸಿ.", high: "ಅತ್ಯಂತ ಎಚ್ಚರಿಕೆಯಿಂದ ಚಾಲನೆ ಮಾಡಿ.", medium: "ಸಾಮಾನ್ಯ ಎಚ್ಚರಿಕೆ.", low: "ವಲಯ ಸುರಕ್ಷಿತವಾಗಿ ಕಾಣುತ್ತದೆ." },
    conditions: { time: "ಸಮಯ", weather: "ಹವಾಮಾನ", road: "ರಸ್ತೆ ಸ್ಥಿತಿ", traffic: "ಸಂಚಾರ" },
    options: { peakMorning: "ಬೆಳಿಗ್ಗೆ ಪೀಕ್ (7-10)", afternoon: "ಮಧ್ಯಾಹ್ನ", peakEvening: "ಸಂಜೆ ಪೀಕ್ (5-9)", lateNight: "ತಡ ರಾತ್ರಿ", earlyMorning: "ಮುಂಜಾನೆ", clear: "ಸ್ಪಷ್ಟ", lightRain: "ಹಗುರ ಮಳೆ", heavyRain: "ಭಾರೀ ಮಳೆ", fog: "ಮಂಜು", denseFog: "ದಟ್ಟ ಮಂಜು", extremeHeat: "ಅತ್ಯಧಿಕ ಬಿಸಿ", good: "ಒಳ್ಳೆಯದು", minorDamage: "ಸಣು ಹಾನಿ", potholes: "ಗುಂಡಿಗಳು", waterlogged: "ನೀರು ನಿಂತಿದೆ", construction: "ನಿರ್ಮಾಣ ವಲಯ", severelyDamaged: "ಗಂಭೀರ ಹಾನಿ", low: "ಕಡಿಮೆ", moderate: "ಮಧ್ಯಮ", heavy: "ಭಾರೀ", stopGo: "ನಿಲ್ಲಿಸಿ-ಹೋಗಿ", accidentInduced: "ಅಪಘಾತ ಕಾರಣ" },
    alerts: { wetRoad: "ಪೀಕ್ ಸಮಯ + ಒದ್ದೆ ರಸ್ತೆ", poorVisibility: "ರಾತ್ರಿ + ಕಡಿಮೆ ದೃಷ್ಟಿ", construction: "ನಿರ್ಮಾಣ ಸಕ್ರಿಯ", traffic: "ಮಧ್ಯಮ ಸಂಚಾರ", slick: "ಹಗುರ ಮಳೆ", visibility: "ದೃಷ್ಟಿ ಕಡಿಮೆ", now: "ಈಗ", minAgo: "{{count}} ನಿಮಿ ಹಿಂದೆ" },
  },
  legalPage: {
    title: "ಕಾನೂನು ಮಾಹಿತಿ", subtitle: "ಭಾರತೀಯ ಮೋಟಾರ್ ವಾಹನ ಕಾಯ್ದೆ 2019 ಸಂಚಾರ ನಿಯಮಗಳು", prototypeTitle: "ಪ್ರೋಟೋಟೈಪ್ ಮಾಡ್ಯೂಲ್", prototype: "ಇದು ಸ್ಥಿರ ಉಲ್ಲೇಖ. ಅಧಿಕೃತ ಮೂಲಗಳಿಂದ ಪರಿಶೀಲಿಸಿ.", searchPlaceholder: "ಕಾನೂನುಗಳು, ವಿಭಾಗಗಳು, ಟ್ಯಾಗ್‌ಗಳು ಹುಡುಕಿ...", category: "ವರ್ಗ", quickFacts: "ತ್ವರಿತ ವಾಸ್ತವಗಳು", futureScope: "ಭವಿಷ್ಯ ವ್ಯಾಪ್ತಿ", futureScopeText: "GPS ಆಧಾರಿತ ರಾಜ್ಯ/ನಗರ ನಿಯಮಗಳು ತೋರಿಸಲಾಗುತ್ತದೆ.", showing: "ತೋರಿಸಲಾಗುತ್ತಿದೆ", ofRules: "{{count}} ನಿಯಮಗಳಲ್ಲಿ", clearSearch: "ಹುಡುಕಾಟ ತೆರವು", noMatch: "ಹೊಂದಾಣಿಕೆಯ ಕಾನೂನು ಇಲ್ಲ", firstOffence: "ಮೊದಲ ಅಪರಾಧ", repeatOffence: "ಪುನರಾವೃತ್ತ ಅಪರಾಧ", imprisonment: "ಜೈಲು: {{term}}",
    categories: { all: "ಎಲ್ಲಾ", speed: "ವೇಗ", safety: "ಸುರಕ್ಷತೆ", signals: "ಸಿಗ್ನಲ್‌ಗಳು", driving: "ಚಾಲನೆ", mobile: "ಮೊಬೈಲ್", lane: "ಲೇನ್", overloading: "ಓವರ್ ಲೋಡ್", insurance: "ವಿಮೆ", documents: "ದಾಖಲೆಗಳು", impairment: "ಮದ್ಯ" },
    facts: { maxFine: "ಗರಿಷ್ಠ ದಂಡ", drunkMax: "ಮದ್ಯಪಾನ ಗರಿಷ್ಠ", listed: "ಪಟ್ಟಿ ಮಾಡಿದ ಅಪರಾಧಗಳು", actVersion: "ಕಾಯ್ದೆ ಆವೃತ್ತಿ" },
    factsValues: { maxFine: "₹20,000", drunkMax: "₹15,000+", listed: "{{count}} ಕಾನೂನುಗಳು", actVersion: "MV Act 2019" },
    lawEntries: lawEntries(lawTexts),
  },
  sosModal: {
    ariaLabel: "ತುರ್ತು SOS ಎಚ್ಚರಿಕೆ", badge: "SOS", close: "ಮುಚ್ಚಿ", seconds: "ಸೆಕೆಂಡುಗಳು", confirmIntro: "ತುರ್ತು SOS ನಿಮ್ಮ ", liveLocation: "ಲೈವ್ ಸ್ಥಳ", confirmMiddle: " ಜೊತೆ ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಮತ್ತು ", emergencyContacts: "ತುರ್ತು ಸಂಪರ್ಕಗಳಿಗೆ", confirmEnd: " ಕಳುಹಿಸಲಾಗುತ್ತದೆ.", cancel: "ರದ್ದು", sendNow: "ಈಗ ಕಳುಹಿಸಿ",
    stages: { confirm: "ತುರ್ತು ಎಚ್ಚರಿಕೆ", locating: "ನಿಮ್ಮನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ…", sending: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…", sent: "ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗಿದೆ" },
    acquiringGps: "GPS ಸಿಗ್ನಲ್ ಪಡೆಯಲಾಗುತ್ತಿದೆ", keepOpen: "ಅಪ್ ತೆರೆದಿಡಿ…", searchingSatellites: "ಉಪಗ್ರಹಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ", contactingServices: "ತುರ್ತು ಸೇವೆಗಳನ್ನು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ", notifyingUnits: "ಹತ್ತಿರದ ಘಟಕಗಳಿಗೆ ತಿಳಿಸಲಾಗುತ್ತಿದೆ…", alertSent: "ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗಿದೆ", servicesNotified: "ತುರ್ತು ಸೇವೆಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ", geoNotSupported: "ಜಿಯೋಲೊಕೇಶನ್ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.", geoFailed: "GPS ಪ್ರವೇಶ ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.", defaultLocation: "ನವ ದೆಹಲಿ (ಡೀಫಾಲ್ಟ್)", approxLocation: "ನವ ದೆಹಲಿ (ಅಂದಾಜು)", ambulanceEta: "ಆಂಬ್ಯುಲೆನ್ಸ್ ETA", unitDispatched: "ಘಟಕ ಕಳುಹಿಸಲಾಗಿದೆ", nearbyHospitals: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು", away: "ದೂರ", done: "ಮುಗಿದಿದೆ", callHospital: "{{name}} ಕರೆ",
  },
  mapUi: { yourLocation: "ನಿಮ್ಮ ಸ್ಥಳ", noApiKey: "Google Maps API ಕೀ ಇಲ್ಲ.", loadFailed: "Google Maps ಲೋಡ್ ವಿಫಲ.", initialising: "ನಕ್ಷೆ ಪ್ರಾರಂಭವಾಗುತ್ತಿದೆ…", zoomIn: "ಜೂಮ್ ಇನ್", zoomOut: "ಜೂಮ್ ಔಟ್", recenter: "ಮಧ್ಯಕ್ಕೆ ತನ್ನಿ", hospitals: "ಆಸ್ಪತ್ರೆಗಳು", incidents: "ಘಟನೆಗಳು", heatmap: "ಹೀಟ್‌ಮ್ಯಾಪ್", satellite: "ಉಪಗ್ರಹ", map: "ನಕ್ಷೆ", you: "ನೀವು", reportedIssues: "ವರದಿಯಾದ ಸಮಸ್ಯೆಗಳು", searchPlaceholder: "ರಸ್ತೆ, ಪ್ರದೇಶ, ಪ್ರಕಾರ ಹುಡುಕಿ…", all: "ಎಲ್ಲಾ", hotspotsTitle: "ಅಪಘಾತ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು", hotspotsSubtitle: "ಕಳೆದ 30 ದಿನಗಳು", totalIncidents: "ಒಟ್ಟು ಘಟನೆಗಳು", peakHour: "ಪೀಕ್ ಸಮಯ", trending: "ಹೆಚ್ಚುತ್ತಿದೆ ↑", total24h: "ಒಟ್ಟು / 24ಗಂ" },
  locationErrors: { denied: "ಸ್ಥಳ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ. GPS ಸಕ್ರಿಯಗೊಳಿಸಿ.", unavailable: "ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ.", timeout: "ಸ್ಥಳ ವಿನಂತಿ ಸಮಯ ಮೀರಿದೆ.", unknown: "ಅಜ್ಞಾತ ಸ್ಥಳ ದೋಷ." },
  sos: { title: "ತುರ್ತು SOS", description: "ತುರ್ತು ಸಮಯದಲ್ಲಿ ತಕ್ಷಣ ಸಹಾಯ", buttonLabel: "ತುರ್ತಿಗೆ ಒತ್ತಿ", nearbyHospitals: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು", emergencyServices: "ತುರ್ತು ಸೇವೆಗಳು", contactingServices: "ತುರ್ತು ಸೇವೆಗಳನ್ನು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...", locationSharing: "ನಿಮ್ಮ ಸ್ಥಳ ಹಂಚಲಾಗುತ್ತಿದೆ" },
  map: { title: "ನಕ್ಷೆ ನೋಟ", noData: "ತೋರಿಸಲು ಘಟನೆಗಳಿಲ್ಲ", zoomToFit: "ಹೊಂದಾಣಿಕೆ ಜೂಮ್", currentLocation: "ಪ್ರಸ್ತುತ ಸ್ಥಳ" },
};
