import { lawEntries } from "./shared-law-fines.mjs";

const lawTexts = {
  speeding: { title: "ഓവർ സ്പീഡ്", desc: "ഹൈവേ, നഗരം അല്ലെങ്കിൽ സ്കൂൾ മേഖലകളിൽ നിശ്ചിത വേഗ പരിധി മീർന്ന് ഓടിക്കൽ." },
  dangerous: { title: "അപകടകരമായ ഓട്ടം", desc: "മറ്റുള്ളവരുടെ ജീവനോ സ്വത്തിനോ അപകടം ഉണ്ടാക്കുന്ന രീതിയിൽ ഓടിക്കൽ." },
  dui: { title: "മദ്യപാന ഓട്ടം", desc: "രക്തത്തിൽ 30mg/100ml ന് മുകളിൽ ആൽക്കഹോൾ ഉപയോഗിച്ച് ഓടിക്കൽ." },
  seatbelt: { title: "സീറ്റ് ബെൽറ്റ് ലംഘനം", desc: "വാഹനം ഓടിക്കുമ്പോൾ സീറ്റ് ബെൽറ്റ് ധരിക്കാതിരിക്കൽ." },
  helmet: { title: "ഹെൽമെറ്റ് ധരിക്കാതിരിക്കൽ", desc: "രണ്ട് ചക്ര വാഹനത്തിൽ ISI ഹെൽമെറ്റ് ധരിക്കാതിരിക്കൽ." },
  redLight: { title: "ചുവന്ന ലൈറ്റ് മറികടക്കൽ", desc: "സ്റ്റോപ്പ് ലൈനിൽ നിന്ന് നിർത്താതെ ചുവന്ന സിഗ്നൽ കടക്കൽ." },
  mobile: { title: "ഓട്ടത്തിനിടെ മൊബൈൽ", desc: "ഓടിക്കുമ്പോൾ കയ്യിൽ മൊബൈൽ ഉപയോഗം." },
  wrongSide: { title: "തെറ്റായ വശത്ത് ഓട്ടം", desc: "റോഡിന്റെ തെറ്റായ വശത്ത് അല്ലെങ്കിൽ വൺ-വേ ൽ എതിർ ദിശയിൽ ഓടിക്കൽ." },
  overloading: { title: "ഓവർ ലോഡിംഗ്", desc: "രജിസ്റ്റർ ചെയ്ത ശേഷി മീർന്ന് യാത്രക്കാരോ സാധനങ്ങളോ." },
  insurance: { title: "ഇൻഷുറൻസ് ഇല്ലാതെ", desc: "സാധുതയുള്ള തേർഡ്-പാർട്ടി ഇൻഷുറൻസ് ഇല്ലാതെ പൊതു റോഡിൽ ഓടിക്കൽ." },
  licence: { title: "ലൈസൻസ് ഇല്ലാതെ", desc: "സാധുതയുള്ള ഡ്രൈവിംഗ് ലൈസൻസ് ഇല്ലാതെ വാഹനം ഓടിക്കൽ." },
  racing: { title: "അനധികൃത റേസിംഗ്", desc: "സർക്കാർ അനുമതി ഇല്ലാതെ പൊതു റോഡിൽ വേഗ പരിശീലനം." },
};

export default {
  dashboardLive: {
    subtitlePrefix: "തത്സമയ റോഡ് സുരക്ഷാ വിശകലനം",
    activeIncidents: "സജീവ സംഭവങ്ങൾ",
    sinceYesterday: "ഇന്നലെ മുതൽ 3 കൂടുതൽ",
    issuesReported: "റിപ്പോർട്ട് ചെയ്ത പ്രശ്നങ്ങൾ",
    today: "ഇന്ന് 12",
    sosActivations: "SOS സജീവീകരണങ്ങൾ",
    thisMonth: "ഈ മാസം",
    resolvedIssues: "പരിഹരിച്ച പ്രശ്നങ്ങൾ",
    resolutionRate: "പരിഹാര നിരക്ക്",
    accidentHotspots: "അപകട ഹോട്ട്സ്പോട്ടുകൾ",
    topZones: "ടോപ്പ് 5 മേഖലകൾ · കഴിഞ്ഞ 30 ദിവസം",
    live: "ലൈവ്",
    recentReports: "സമീപകാല റിപ്പോർട്ടുകൾ",
    liveMapView: "ലൈവ് മാപ്പ്",
    connectMaps: "Google Maps API ബന്ധിപ്പിക്കുക",
    severity: { critical: "ഗുരുതരം", high: "ഉയർന്ന", medium: "ഇടത്തരം", low: "കുറഞ്ഞ" },
    status: { pending: "തീർപ്പാക്കാത്ത", verified: "സ്ഥിരീകരിച്ചു", inProgress: "നടന്നുകൊണ്ടിരിക്കുന്നു", resolved: "പരിഹരിച്ചു" },
    issueTypes: { pothole: "കുഴി", waterlogging: "ജലനിറയൽ", damagedRoad: "തകർന്ന റോഡ്", brokenDivider: "തകർന്ന ഡിവൈഡർ", missingSign: "കാണാതായ അടയാളം" },
  },
  reportIssuePage: {
    title: "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
    subtitle: "AI കണ്ടെത്തലിനായി റോഡ് ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    uploadTitle: "റോഡ് ചിത്രം അപ്‌ലോഡ്",
    uploadSubtitle: "AI കണ്ടെത്തൽ ആരംഭിക്കാൻ ചിത്രം ഡ്രോപ്പ് ചെയ്യുക അല്ലെങ്കിൽ തിരഞ്ഞെടുക്കുക.",
    issueType: "പ്രശ്ന തരം",
    severity: "തീവ്രത",
    roadLocation: "റോഡ് / സ്ഥാനം *",
    roadPlaceholder: "ഉദാ. NH-48, KM 14 മഹിപാൽപൂർ അടുത്ത്",
    area: "മേഖല",
    areaPlaceholder: "ഉദാ. ദക്ഷിണ ഡൽഹി",
    notes: "അധിക കുറിപ്പുകൾ",
    notesPlaceholder: "പ്രശ്നം, കാലാവധി, അപകടം വിവരിക്കുക...",
    submit: "റിപ്പോർട്ട് സമർപ്പിക്കുക",
    submittedTitle: "റിപ്പോർട്ട് സമർപ്പിച്ചു",
    submittedMessage: "നിങ്ങളുടെ റോഡ് പ്രശ്നം രേഖപ്പെടുത്തി. ഇന്ത്യൻ റോഡുകൾ സുരക്ഷിതമാക്കാൻ സഹായത്തിന് നന്ദി.",
    reportAnother: "മറ്റൊരു റിപ്പോർട്ട്",
    viewDashboard: "ഡാഷ്ബോർഡ് കാണുക",
    issueTypes: { pothole: "കുഴി", damage: "തകർന്ന റോഡ്", water: "ജലനിറയൽ", divider: "തകർന്ന ഡിവൈഡർ", sign: "കാണാതായ അടയാളം", other: "മറ്റുള്ളവ" },
    severityLevels: { critical: "ഗുരുതരം", high: "ഉയർന്ന", medium: "ഇടത്തരം", low: "കുറഞ്ഞ" },
    simulated: { pothole: "ആഴത്തിലുള്ള കുഴി ഉയർന്ന വിശ്വാസത്തോടെ കണ്ടെത്തി.", damage: "റോഡ് വിള്ളലുകൾ കണ്ടെത്തി.", water: "റോഡിൽ നിന്ന നീർ കണ്ടെത്തി.", surface: "പൊതുവായ റോഡ് തേയ്മാനം. പരിപാലനം ആവശ്യം." },
  },
  uploader: { invalidImage: "സാധുതയുള്ള ചിത്ര ഫയൽ തിരഞ്ഞെടുക്കുക.", selected: "തിരഞ്ഞെടുത്തത്: {{fileName}}", supportedFormats: "JPG, PNG, WEBP എന്നിവ പിന്തുണയ്ക്കുന്നു.", previewAlt: "റോഡ് പ്രശ്ന പ്രിവ്യൂ", dropHere: "നിങ്ങളുടെ ചിത്രം ഇവിടെ വിടുക", chooseHint: "അല്ലെങ്കിൽ ഉപകരണത്തിൽ നിന്ന് തിരഞ്ഞെടുക്കുക", chooseImage: "ചിത്രം തിരഞ്ഞെടുക്കുക" },
  detector: { analyzingTitle: "ചിത്ര വിശകലനം", analyzingDescription: "AI റോഡ് നാശ പാറ്റേണുകൾ പരിശോധിക്കുന്നു.", running: "കണ്ടെത്തൽ നടക്കുന്നു...", failedTitle: "കണ്ടെത്തൽ പരാജയം", emptyTitle: "ഇനിയും കണ്ടെത്തൽ ഇല്ല", emptyDescription: "AI വിലയിരുത്തലിനായി ചിത്രം അപ്‌ലോഡ് ചെയ്യുക.", resultTitle: "AI കണ്ടെത്തൽ ഫലം", fallbackLabel: "റോഡ് പ്രശ്നം കണ്ടെത്തി", severityLabel: "{{severity}} തീവ്രത", fallbackDescription: "ചിത്രം വിശകലനം ചെയ്ത് വർഗ്ഗീകരിച്ചു.", confidence: "വിശ്വാസം", fallbackType: "റോഡ് നാശ വർഗ്ഗീകരണം", uploadedPreview: "അപ്‌ലോഡ് പ്രിവ്യൂ", uploadedAlt: "അപ്‌ലോഡ് ചെയ്ത റോഡ് പ്രശ്നം" },
  sosPage: {
    title: "അടിയന്തര SOS", subtitle: "ലൈവ് സ്ഥാനത്തോടെ ഒറ്റ ടാപ്പ് അലർട്ട്", buttonSub: "അടിയന്തരം", ready: "സിസ്റ്റം തയ്യാർ · GPS സജീവം", locating: "സ്ഥാനം ലഭിക്കുന്നു...", dispatched: "അലർട്ട് അയച്ചു", alertSent: "അലർട്ട് അയച്ചു", servicesEta: "സേവനങ്ങളെ അറിയിച്ചു · ETA ~6 മിനി", reset: "റീസെറ്റ്", helper: "നിങ്ങളുടെ സ്ഥാനം അടിയന്തര സേവനങ്ങൾക്ക് അയയ്ക്കാൻ SOS അമർത്തുക.", numbers: "അടിയന്തര നമ്പറുകൾ", whatNext: "അടുത്തത് എന്ത് സംഭവിക്കും",
    contacts: { police: "പോലീസ്", ambulance: "ആംബുലൻസ്", fire: "അഗ്നിശമനം", road: "റോഡ് ഹെൽപ്‌ലൈൻ" },
    steps: { capture: "നിങ്ങളുടെ GPS കോഓർഡിനേറ്റുകൾ പിടിച്ച് അയയ്ക്കുന്നു.", hospitals: "സമീപ ആശുപത്രികൾ കണ്ടെത്തുന്നു.", ambulance: "ആംബുലൻസ് അയയ്ക്കുന്നു.", sms: "അടിയന്തര ബന്ധുക്കൾക്ക് SMS അയയ്ക്കുന്നു." },
  },
  riskPage: {
    title: "റിസ്ക് അലർട്ടുകൾ", subtitle: "നിങ്ങളുടെ മാർഗത്തിനുള്ള ML അപകട റിസ്ക്", predictor: "റിസ്ക് പ്രവചനം", predictorHelp: "സാഹചര്യങ്ങൾ സജ്ജമാക്കുക. മോഡൽ സ്കോർ നൽകും.", select: "തിരഞ്ഞെടുക്കുക...", analyze: "റിസ്ക് വിശകലനം", analyzing: "വിശകലനം...", riskFactors: "റിസ്ക് ഘടകങ്ങൾ", currentScore: "നിലവിലെ മേഖല റിസ്ക് സ്കോർ", feed: "ലൈവ് അലർട്ട് ഫീഡ്", scoreSuffix: "/100",
    labels: { critical: "ഗുരുതരം", highRisk: "ഉയർന്ന റിസ്ക്", moderate: "ഇടത്തരം", lowRisk: "കുറഞ്ഞ റിസ്ക്" },
    advice: { critical: "സാധ്യമെങ്കിൽ ഈ മേഖല ഒഴിവാക്കുക.", high: "വളരെ ശ്രദ്ധയോടെ ഓടിക്കുക.", medium: "സാധാരണ മുൻകരുതലുകൾ.", low: "മേഖല സുരക്ഷിതമായി തോന്നുന്നു." },
    conditions: { time: "സമയം", weather: "കാലാവസ്ഥ", road: "റോഡ് നില", traffic: "ട്രാഫിക്" },
    options: { peakMorning: "രാവിലെ പീക്ക് (7-10)", afternoon: "ഉച്ച", peakEvening: "വൈകുന്നേരം പീക്ക് (5-9)", lateNight: "രാത്രി വൈകി", earlyMorning: "പ്രഭാതം", clear: "തെളിവ്", lightRain: "ലഘു മഴ", heavyRain: "കനത്ത മഴ", fog: "മൂടൽ", denseFog: "ഇടതൂരമായ മൂടൽ", extremeHeat: "അത്യധിക ചൂട്", good: "നല്ലത്", minorDamage: "ചെറിയ നാശം", potholes: "കുഴികൾ", waterlogged: "ജലനിറഞ്ഞ", construction: "നിർമാണ മേഖല", severelyDamaged: "ഗുരുതര നാശം", low: "കുറഞ്ഞ", moderate: "ഇടത്തരം", heavy: "കനത്ത", stopGo: "നിർത്തി-പോകുക", accidentInduced: "അപകട കാരണം" },
    alerts: { wetRoad: "പീക്ക് സമയം + നനഞ്ഞ റോഡ്", poorVisibility: "രാത്രി + കുറഞ്ഞ ദൃശ്യം", construction: "നിർമാണം സജീവം", traffic: "ഇടത്തരം ട്രാഫിക്", slick: "ലഘു മഴ", visibility: "ദൃശ്യം കുറഞ്ഞു", now: "ഇപ്പോൾ", minAgo: "{{count}} മിനി മുമ്പ്" },
  },
  legalPage: {
    title: "നിയമ വിവരം", subtitle: "ഇന്ത്യൻ മോട്ടർ വാഹന നിയമം 2019 ട്രാഫിക് നിയമങ്ങൾ", prototypeTitle: "പ്രോട്ടോടൈപ്പ് മൊഡ്യൂൾ", prototype: "ഇത് സ്ഥിരമായ റഫറൻസ്. ഔദ്യോഗിക ഉറവിടങ്ങളിൽ പരിശോധിക്കുക.", searchPlaceholder: "നിയമങ്ങൾ, വിഭാഗങ്ങൾ, ടാഗുകൾ തിരയുക...", category: "വിഭാഗം", quickFacts: "പെട്ടെന്നുള്ള വസ്തുതകൾ", futureScope: "ഭാവി വ്യാപ്തി", futureScopeText: "GPS അടിസ്ഥാനത്തിൽ സംസ്ഥാന/നഗര നിയമങ്ങൾ കാണിക്കും.", showing: "കാണിക്കുന്നു", ofRules: "{{count}} നിയമങ്ങളിൽ", clearSearch: "തിരയൽ മായ്ക്കുക", noMatch: "പൊരുത്തപ്പെടുന്ന നിയമം ഇല്ല", firstOffence: "ആദ്യ അപരാധം", repeatOffence: "ആവർത്തന അപരാധം", imprisonment: "തടവ്: {{term}}",
    categories: { all: "എല്ലാം", speed: "വേഗത", safety: "സുരക്ഷ", signals: "സിഗ്നലുകൾ", driving: "ഓട്ടം", mobile: "മൊബൈൽ", lane: "ലേൻ", overloading: "ഓവർ ലോഡ്", insurance: "ഇൻഷുറൻസ്", documents: "രേഖകൾ", impairment: "മദ്യം" },
    facts: { maxFine: "പരമാവധി പിഴ", drunkMax: "മദ്യപാന പരമാവധി", listed: "പട്ടികപ്പെട്ട അപരാധങ്ങൾ", actVersion: "നിയമ പതിപ്പ്" },
    factsValues: { maxFine: "₹20,000", drunkMax: "₹15,000+", listed: "{{count}} നിയമങ്ങൾ", actVersion: "MV Act 2019" },
    lawEntries: lawEntries(lawTexts),
  },
  sosModal: {
    ariaLabel: "അടിയന്തര SOS അലർട്ട്", badge: "SOS", close: "അടയ്ക്കുക", seconds: "സെക്കൻഡ്", confirmIntro: "അടിയന്തര SOS നിങ്ങളുടെ ", liveLocation: "ലൈവ് സ്ഥാനം", confirmMiddle: " ഉപയോഗിച്ച് അടിയന്തര സേവനങ്ങൾക്കും ", emergencyContacts: "അടിയന്തര ബന്ധുക്കൾക്കും", confirmEnd: " അയയ്ക്കും.", cancel: "റദ്ദാക്കുക", sendNow: "ഇപ്പോൾ അയയ്ക്കുക",
    stages: { confirm: "അടിയന്തര അലർട്ട്", locating: "നിങ്ങളെ കണ്ടെത്തുന്നു…", sending: "അയയ്ക്കുന്നു…", sent: "അലർട്ട് അയച്ചു" },
    acquiringGps: "GPS സിഗ്നൽ ലഭിക്കുന്നു", keepOpen: "ആപ്പ് തുറന്ന് വയ്ക്കുക…", searchingSatellites: "ഉപഗ്രഹങ്ങൾ തിരയുന്നു", contactingServices: "അടിയന്തര സേവനങ്ങളെ ബന്ധപ്പെടുന്നു", notifyingUnits: "സമീപ യൂണിറ്റുകളെ അറിയിക്കുന്നു…", alertSent: "അലർട്ട് അയച്ചു", servicesNotified: "അടിയന്തര സേവനങ്ങളെ അറിയിച്ചു", geoNotSupported: "ജിയോലൊക്കേഷൻ പിന്തുണയ്ക്കുന്നില്ല.", geoFailed: "GPS പ്രവേശനം സാധ്യമല്ല.", defaultLocation: "ന്യൂ ഡൽഹി (ഡിഫോൾട്ട്)", approxLocation: "ന്യൂ ഡൽഹി (ഏകദേശം)", ambulanceEta: "ആംബുലൻസ് ETA", unitDispatched: "യൂണിറ്റ് അയച്ചു", nearbyHospitals: "സമീപ ആശുപത്രികൾ", away: "ദൂരം", done: "പൂർത്തി", callHospital: "{{name}} വിളിക്കുക",
  },
  mapUi: { yourLocation: "നിങ്ങളുടെ സ്ഥാനം", noApiKey: "Google Maps API കീ ഇല്ല.", loadFailed: "Google Maps ലോഡ് പരാജയം.", initialising: "മാപ്പ് ആരംഭിക്കുന്നു…", zoomIn: "സൂം ഇൻ", zoomOut: "സൂം ഔട്ട്", recenter: "മധ്യത്തിൽ കൊണ്ടുവരിക", hospitals: "ആശുപത്രികൾ", incidents: "സംഭവങ്ങൾ", heatmap: "ഹീറ്റ്‌മാപ്പ്", satellite: "ഉപഗ്രഹം", map: "മാപ്പ്", you: "നിങ്ങൾ", reportedIssues: "റിപ്പോർട്ട് ചെയ്ത പ്രശ്നങ്ങൾ", searchPlaceholder: "റോഡ്, മേഖല, തരം തിരയുക…", all: "എല്ലാം", hotspotsTitle: "അപകട ഹോട്ട്സ്പോട്ടുകൾ", hotspotsSubtitle: "കഴിഞ്ഞ 30 ദിവസം", totalIncidents: "മൊത്തം സംഭവങ്ങൾ", peakHour: "പീക്ക് സമയം", trending: "വർദ്ധന ↑", total24h: "മൊത്തം / 24മണി" },
  locationErrors: { denied: "സ്ഥാന പ്രവേശനം നിരസിച്ചു. GPS പ്രവർത്തനക്ഷമമാക്കുക.", unavailable: "സ്ഥാനം ലഭ്യമല്ല.", timeout: "സ്ഥാന അഭ്യർത്ഥന സമയം കഴിഞ്ഞു.", unknown: "അജ്ഞാത സ്ഥാന പിശക്." },
  sos: { title: "അടിയന്തര SOS", description: "അടിയന്തര സമയത്ത് ഉടനടി സഹായം", buttonLabel: "അടിയന്തരത്തിന് അമർത്തുക", nearbyHospitals: "സമീപ ആശുപത്രികൾ", emergencyServices: "അടിയന്തര സേവനങ്ങൾ", contactingServices: "അടിയന്തര സേവനങ്ങളെ ബന്ധപ്പെടുന്നു...", locationSharing: "നിങ്ങളുടെ സ്ഥാനം പങ്കിടുന്നു" },
  map: { title: "മാപ്പ് കാഴ്ച", noData: "കാണിക്കാൻ സംഭവങ്ങളില്ല", zoomToFit: "ഫിറ്റ് ആയി സൂം", currentLocation: "നിലവിലെ സ്ഥാനം" },
};
