import { lawEntries } from "./shared-law-fines.mjs";

const lawTexts = {
  speeding: { title: "வேக மீறல்", desc: "நெடுஞ்சாலை, நகர்ப்புறம் அல்லது பள்ளி மண்டலங்களில் விதிக்கப்பட்ட வேக வரம்பை மீறி ஓட்டுதல்." },
  dangerous: { title: "ஆபத்தான ஓட்டம்", desc: "பிறரின் உயிர் அல்லது சொத்துக்கு அபாயம் விளைவிக்கும் வகையில் ஓட்டுதல். போட்டி மற்றும் அவசர ஓட்டம் உட்பட." },
  dui: { title: "குடிபோதை ஓட்டம்", desc: "இரத்தத்தில் 30mg/100ml க்கு மேல் ஆல்கஹால் உடன் ஓட்டுதல்." },
  seatbelt: { title: "இருக்கை பட்டை மீறல்", desc: "வாகனம் நகரும் போது ஓட்டுநர் அல்லது முன் இருக்கை பயணி இருக்கை பட்டை அணியாமல் இருத்தல்." },
  helmet: { title: "ஹெல்மெட் அணியாதது", desc: "இரு சக்கர வாகன ஓட்டுநர் அல்லது பின் இருக்கை பயணி ISI சான்றிதழ் ஹெல்மெட் அணியாதது." },
  redLight: { title: "சிகப்பு விளக்கு மீறல்", desc: "நிறுத்தக் கோட்டில் நிற்காமல் சிகப்பு சமிக்கையை கடந்து செல்லுதல்." },
  mobile: { title: "ஓட்டும் போது மொபைல்", desc: "ஓட்டும் போது கையில் மொபைல் பயன்படுத்துதல்." },
  wrongSide: { title: "தவறான பக்க ஓட்டம்", desc: "சாலையின் தவறான பக்கம் அல்லது ஒரு வழி தெருவில் எதிர் திசையில் ஓட்டுதல்." },
  overloading: { title: "அதிக சுமை", desc: "பதிவு செய்த கொள்ளளவை மீறி பயணிகள் அல்லது சரக்கு ஏற்றுதல்." },
  insurance: { title: "காப்பீடு இல்லாமல் ஓட்டுதல்", desc: "செல்லுபடியாகும் மூன்றாம் தரப்பு காப்பீடு இல்லாமல் பொது சாலையில் வாகனம் ஓட்டுதல்." },
  licence: { title: "உரிமம் இல்லாமல் ஓட்டுதல்", desc: "செல்லுபடியாகும் ஓட்டுநர் உரிமம் இல்லாமல் வாகனம் ஓட்டுதல்." },
  racing: { title: "அனுமதியில்லா போட்டி", desc: "அரசு எழுத்துப்பூர்வ அனுமதி இல்லாமல் பொது சாலையில் வேக போட்டி." },
};

export default {
  dashboardLive: {
    subtitlePrefix: "நேரடி சாலை பாதுகாப்பு பகுப்பாய்வு",
    activeIncidents: "செயலில் உள்ள சம்பவங்கள்",
    sinceYesterday: "நேற்றிலிருந்து 3 அதிகம்",
    issuesReported: "புகாரளிக்கப்பட்ட பிரச்சனைகள்",
    today: "இன்று 12",
    sosActivations: "SOS செயல்படுத்தல்கள்",
    thisMonth: "இந்த மாதம்",
    resolvedIssues: "தீர்க்கப்பட்ட பிரச்சனைகள்",
    resolutionRate: "தீர்வு விகிதம்",
    accidentHotspots: "விபத்து ஹாட்ஸ்பாட்கள்",
    topZones: "முதல் 5 மண்டலங்கள் · கடந்த 30 நாட்கள்",
    live: "நேரடி",
    recentReports: "சமீபத்திய அறிக்கைகள்",
    liveMapView: "நேரடி வரைபடம்",
    connectMaps: "இயக்க Google Maps API ஐ இணைக்கவும்",
    severity: { critical: "முக்கிய", high: "உயர்", medium: "நடுத்தர", low: "குறைந்த" },
    status: { pending: "நிலுவை", verified: "சரிபார்க்கப்பட்டது", inProgress: "நடந்து கொண்டிருக்கிறது", resolved: "தீர்க்கப்பட்டது" },
    issueTypes: { pothole: "பள்ளம்", waterlogging: "நீர் தேங்கல்", damagedRoad: "சேதமடைந்த சாலை", brokenDivider: "உடைந்த பிரிப்பான்", missingSign: "காணாமல் போன அடையாளம்" },
  },
  reportIssuePage: {
    title: "பிரச்சனை புகாரளிக்கவும்",
    subtitle: "AI கண்டறிதலுக்கு சாலை படத்தை பதிவேற்றவும்",
    uploadTitle: "சாலை படம் பதிவேற்றம்",
    uploadSubtitle: "AI கண்டறிதலைத் தொடங்க படத்தை இழுத்து விடுங்கள் அல்லது தேர்வு செய்யுங்கள்.",
    issueType: "பிரச்சனை வகை",
    severity: "தீவிரம்",
    roadLocation: "சாலை / இடம் *",
    roadPlaceholder: "எ.கா. NH-48, KM 14 மஹிபால்பூர் அருகில்",
    area: "பகுதி / உள்ளூர்",
    areaPlaceholder: "எ.கா. தெற்கு டெல்லி",
    notes: "கூடுதல் குறிப்புகள்",
    notesPlaceholder: "பிரச்சனை, காலம், அபாய நிலை விவரிக்கவும்...",
    submit: "அறிக்கை சமர்ப்பிக்கவும்",
    submittedTitle: "அறிக்கை சமர்ப்பிக்கப்பட்டது",
    submittedMessage: "உங்கள் சாலை பிரச்சனை பதிவு செய்யப்பட்டது. இந்திய சாலைகளை பாதுகாப்பாக்க உதவியதற்கு நன்றி.",
    reportAnother: "மற்றொரு புகார்",
    viewDashboard: "டாஷ்போர்டைப் பார்",
    issueTypes: { pothole: "பள்ளம்", damage: "சேதமடைந்த சாலை", water: "நீர் தேங்கல்", divider: "உடைந்த பிரிப்பான்", sign: "காணாமல் போன அடையாளம்", other: "மற்றவை" },
    severityLevels: { critical: "முக்கிய", high: "உயர்", medium: "நடுத்தர", low: "குறைந்த" },
    simulated: { pothole: "ஆழமான பள்ளம் உயர் நம்பிக்கையுடன் கண்டறியப்பட்டது. உடனடி பழுது பரிந்துரை.", damage: "சாலை விரிசல் மற்றும் தாழ்வு கண்டறியப்பட்டது.", water: "சாலையில் நிற்கும் நீர் கண்டறியப்பட்டது.", surface: "பொதுவான சாலை அணிப்பு. பராமரிப்பு தேவை." },
  },
  uploader: { invalidImage: "செல்லுபடியாகும் பட கோப்பைத் தேர்ந்தெடுக்கவும்.", selected: "தேர்ந்தெடுக்கப்பட்டது: {{fileName}}", supportedFormats: "JPG, PNG, WEBP மற்றும் பொதுவான வடிவங்கள் ஆதரிக்கப்படுகின்றன.", previewAlt: "சாலை பிரச்சனை முன்னோட்டம்", dropHere: "உங்கள் படத்தை இங்கே விடுங்கள்", chooseHint: "அல்லது சாதனத்திலிருந்து தேர்வு செய்யுங்கள்", chooseImage: "படம் தேர்வு" },
  detector: { analyzingTitle: "படம் பகுப்பாய்வு", analyzingDescription: "AI சாலை சேத வடிவங்களை சரிபார்க்கிறது.", running: "கண்டறிதல் நடைபெறுகிறது...", failedTitle: "கண்டறிதல் தோல்வி", emptyTitle: "இன்னும் கண்டறிதல் இல்லை", emptyDescription: "AI மதிப்பீட்டிற்கு படம் பதிவேற்றவும்.", resultTitle: "AI கண்டறிதல் முடிவு", fallbackLabel: "சாலை பிரச்சனை கண்டறியப்பட்டது", severityLabel: "{{severity}} தீவிரம்", fallbackDescription: "படம் பகுப்பாய்வு செய்யப்பட்டு வகைப்படுத்தப்பட்டது.", confidence: "நம்பிக்கை", fallbackType: "சாலை சேத வகைப்பாடு", uploadedPreview: "பதிவேற்ற முன்னோட்டம்", uploadedAlt: "பதிவேற்றிய சாலை பிரச்சனை" },
  sosPage: {
    title: "அவசர SOS", subtitle: "நேரடி இடத்துடன் ஒரே தட்டல் அவசர எச்சரிக்கை", buttonSub: "அவசரம்", ready: "அமைப்பு தயார் · GPS செயலில்", locating: "இடம் பெறப்படுகிறது...", dispatched: "எச்சரிக்கை அனுப்பப்பட்டது", alertSent: "எச்சரிக்கை அனுப்பப்பட்டது", servicesEta: "சேவைகள் அறிவிக்கப்பட்டன · ETA ~6 நிமி", reset: "மீட்டமை", helper: "உங்கள் இடத்தை அவசர சேவைகளுக்கு உடனடியாக அனுப்ப SOS அழுத்தவும்.", numbers: "அவசர எண்கள்", whatNext: "அடுத்து என்ன நடக்கும்",
    contacts: { police: "போலீஸ்", ambulance: "ஆம்புலன்ஸ்", fire: "தீயணைப்பு", road: "சாலை உதவி" },
    steps: { capture: "உங்கள் GPS ஆயத்தங்கள் பிடிக்கப்பட்டு அனுப்பப்படுகின்றன.", hospitals: "அருகிலுள்ள மருத்துவமனைகள் கண்டறியப்படுகின்றன.", ambulance: "ஆம்புலன்ஸ் அனுப்பப்படுகிறது.", sms: "அவசர தொடர்புகளுக்கு SMS அனுப்பப்படுகிறது." },
  },
  riskPage: {
    title: "ஆபத்து எச்சரிக்கைகள்", subtitle: "உங்கள் பாதைக்கான ML விபத்து ஆபத்து கணிப்பு", predictor: "ஆபத்து கணிப்பான்", predictorHelp: "நிலைமைகளை அமைக்கவும். மாதிரி ஆபத்து மதிப்பெண் தரும்.", select: "தேர்வு...", analyze: "ஆபத்து பகுப்பாய்வு", analyzing: "பகுப்பாய்வு...", riskFactors: "ஆபத்து காரணிகள்", currentScore: "தற்போதைய மண்டல ஆபத்து மதிப்பெண்", feed: "நேரடி எச்சரிக்கை ஊட்டம்", scoreSuffix: "/100",
    labels: { critical: "முக்கிய", highRisk: "உயர் ஆபத்து", moderate: "நடுத்தர", lowRisk: "குறைந்த ஆபத்து" },
    advice: { critical: "முடிந்தால் இந்த மண்டலத்தை தவிர்க்கவும்.", high: "மிகுந்த எச்சரிக்கையுடன் ஓட்டுங்கள்.", medium: "சாதாரண முன்னெச்சரிக்கை.", low: "மண்டலம் பாதுகாப்பாக தோன்றுகிறது." },
    conditions: { time: "நேரம்", weather: "வானிலை", road: "சாலை நிலை", traffic: "போக்குவரத்து" },
    options: { peakMorning: "காலை உச்சம் (7-10)", afternoon: "மதியம்", peakEvening: "மாலை உச்சம் (5-9)", lateNight: "இரவு தாமதம்", earlyMorning: "அதிகாலை", clear: "தெளிவு", lightRain: "லேசான மழை", heavyRain: "கடும் மழை", fog: "மூடுபனி", denseFog: "அடர்த்தியான மூடுபனி", extremeHeat: "கடும் வெப்பம்", good: "நன்று", minorDamage: "சிறு சேதம்", potholes: "பள்ளங்கள்", waterlogged: "நீர் நிறைந்த", construction: "கட்டுமான மண்டலம்", severelyDamaged: "கடுமையான சேதம்", low: "குறைந்த", moderate: "நடுத்தர", heavy: "அதிக", stopGo: "நிறுத்தி-செல்", accidentInduced: "விபத்து காரணம்" },
    alerts: { wetRoad: "உச்ச நேரம் + ஈர சாலை", poorVisibility: "இரவு + குறைந்த பார்வை", construction: "கட்டுமானம் செயலில்", traffic: "நடுத்தர போக்குவரத்து", slick: "லேசான மழை", visibility: "பார்வை குறைவு", now: "இப்போது", minAgo: "{{count}} நிமி முன்பு" },
  },
  legalPage: {
    title: "சட்ட தகவல்", subtitle: "இந்திய மோட்டார் வாகன சட்டம் 2019 போக்குவரத்து விதிகள்", prototypeTitle: "முன்மாதிரி தொகுதி", prototype: "இது நிலையான குறிப்பு. அதிகாரப்பூர்வ மூலங்களில் சரிபார்க்கவும்.", searchPlaceholder: "சட்டங்கள், பிரிவுகள், குறிச்சொற்கள் தேடல்...", category: "வகை", quickFacts: "விரைவு தகவல்கள்", futureScope: "எதிர்கால வரம்பு", futureScopeText: "GPS அடிப்படையில் மாநில/நகர விதிகள் காட்டப்படும்.", showing: "காட்டப்படுகிறது", ofRules: "{{count}} விதிகளில்", clearSearch: "தேடலை அழி", noMatch: "பொருந்தும் சட்டம் இல்லை", firstOffence: "முதல் குற்றம்", repeatOffence: "மீண்டும் குற்றம்", imprisonment: "சிறை: {{term}}",
    categories: { all: "அனைத்தும்", speed: "வேகம்", safety: "பாதுகாப்பு", signals: "சமிக்கைகள்", driving: "ஓட்டுதல்", mobile: "மொபைல்", lane: "லேன்", overloading: "அதிக சுமை", insurance: "காப்பீடு", documents: "ஆவணங்கள்", impairment: "நசைபோதை" },
    facts: { maxFine: "அதிகபட்ச அபராதம்", drunkMax: "குடிபோதை அதிகபட்சம்", listed: "பட்டியலிடப்பட்ட குற்றங்கள்", actVersion: "சட்ட பதிப்பு" },
    factsValues: { maxFine: "₹20,000", drunkMax: "₹15,000+", listed: "{{count}} சட்டங்கள்", actVersion: "MV Act 2019" },
    lawEntries: lawEntries(lawTexts),
  },
  sosModal: {
    ariaLabel: "அவசர SOS எச்சரிக்கை", badge: "SOS", close: "மூடு", seconds: "வினாடிகள்", confirmIntro: "அவசர SOS உங்கள் ", liveLocation: "நேரடி இடம்", confirmMiddle: " உடன் அவசர சேவைகளுக்கும் ", emergencyContacts: "அவசர தொடர்புகளுக்கும்", confirmEnd: " அனுப்பப்படும்.", cancel: "ரத்து", sendNow: "இப்போது அனுப்பு",
    stages: { confirm: "அவசர எச்சரிக்கை", locating: "உங்களை கண்டறிகிறது…", sending: "அனுப்புகிறது…", sent: "எச்சரிக்கை அனுப்பப்பட்டது" },
    acquiringGps: "GPS சிக்னல் பெறுகிறது", keepOpen: "பயன்பாட்டை திறந்து வைத்திருங்கள்…", searchingSatellites: "செயற்கைக்கோள்கள் தேடல்", contactingServices: "அவசர சேவைகளை தொடர்பு", notifyingUnits: "அருகிலுள்ள அலகுகள் & தொடர்புகள் அறிவிப்பு…", alertSent: "எச்சரிக்கை அனுப்பப்பட்டது", servicesNotified: "அவசர சேவைகள் அறிவிக்கப்பட்டன", geoNotSupported: "இடம் ஆதரிக்கப்படவில்லை — இயல்புநிலை இடம்.", geoFailed: "GPS அணுக முடியவில்லை — தோராயமான இடம்.", defaultLocation: "புது டெல்லி (இயல்பு)", approxLocation: "புது டெல்லி (தோராயம்)", ambulanceEta: "ஆம்புலன்ஸ் ETA", unitDispatched: "அலகு அனுப்பப்பட்டது — நேரடி கண்காணிப்பு", nearbyHospitals: "அருகிலுள்ள மருத்துவமனைகள்", away: "தூரம்", done: "முடிந்தது", callHospital: "{{name}} அழைக்க",
  },
  mapUi: { yourLocation: "உங்கள் இடம்", noApiKey: "Google Maps API விசை இல்லை.", loadFailed: "Google Maps ஏற்றுதல் தோல்வி.", initialising: "வரைபடம் துவங்குகிறது…", zoomIn: "பெரிதாக்கு", zoomOut: "சிறிதாக்கு", recenter: "மையப்படுத்து", hospitals: "மருத்துவமனைகள்", incidents: "சம்பவங்கள்", heatmap: "வெப்ப வரைபடம்", satellite: "செயற்கைக்கோள்", map: "வரைபடம்", you: "நீங்கள்", reportedIssues: "புகாரளிக்கப்பட்ட பிரச்சனைகள்", searchPlaceholder: "சாலை, பகுதி, வகை தேடல்…", all: "அனைத்தும்", hotspotsTitle: "விபத்து ஹாட்ஸ்பாட்கள்", hotspotsSubtitle: "கடந்த 30 நாட்கள் · தானியங்கி புதுப்பிப்பு", totalIncidents: "மொத்த சம்பவங்கள்", peakHour: "உச்ச நேரம்", trending: "அதிகரிப்பு ↑", total24h: "மொத்தம் / 24மணி" },
  locationErrors: { denied: "இட அணுகல் மறுக்கப்பட்டது. உலாவியில் GPS இயக்கவும்.", unavailable: "இடம் கிடைக்கவில்லை. GPS சிக்னல் சரிபார்க்கவும்.", timeout: "இட கோரிக்கை நேரம் முடிந்தது. மீண்டும் முயற்சிக்கவும்.", unknown: "அறியப்படாத இட பிழை." },
  sos: { title: "அவசர SOS", description: "அவசர நிலையில் உடனடி உதவி பெறுங்கள்", buttonLabel: "அவசரத்திற்கு அழுத்தவும்", nearbyHospitals: "அருகிலுள்ள மருத்துவமனைகள்", emergencyServices: "அவசர சேவைகள்", contactingServices: "அவசர சேவைகளை தொடர்பு கொள்கிறது...", locationSharing: "உங்கள் இடம் பகிரப்படுகிறது" },
  map: { title: "வரைபட காட்சி", noData: "காட்ட எந்த சம்பவமும் இல்லை", zoomToFit: "பொருத்தமாக பெரிதாக்கு", currentLocation: "தற்போதைய இடம்" },
};
