import { lawEntries } from "./shared-law-fines.mjs";

const lawTexts = {
  speeding: { title: "ఓవర్ స్పీడ్", desc: "హైవే, పట్టణ లేదా పాఠశాల ప్రాంతాలలో నిర్ణీత వేగ పరిమితిని మించి నడపడం." },
  dangerous: { title: "ప్రమాదకర డ్రైవింగ్", desc: "ఇతరుల ప్రాణం లేదా ఆస్తికి ప్రమాదం కలిగించే విధంగా నడపడం." },
  dui: { title: "మద్యపాన డ్రైవింగ్", desc: "రక్తంలో 30mg/100ml కంటే ఎక్కువ ఆల్కహాల్ తో నడపడం." },
  seatbelt: { title: "సీట్ బెల్ట్ ఉల్లంఘన", desc: "వాహనం నడుస్తున్నప్పుడు సీట్ బెల్ట్ ధరించకపోవడం." },
  helmet: { title: "హెల్మెట్ లేకపోవడం", desc: "రెండు చక్రాల వాహనంలో ISI హెల్మెట్ ధరించకపోవడం." },
  redLight: { title: "ఎరుపు సిగ్నల్ దాటడం", desc: "స్టాప్ లైన్ వద్ద నిలిచే లేకుండా ఎరుపు సిగ్నల్ దాటడం." },
  mobile: { title: "డ్రైవింగ్ లో మొబైల్", desc: "నడుస్తున్నప్పుడు చేతిలో మొబైల్ ఉపయోగం." },
  wrongSide: { title: "తప్పు వైపు నడపడం", desc: "రోడ్డు యొక్క తప్పు వైపు లేదా వన్-వే లో వ్యతిరేక దిశలో నడపడం." },
  overloading: { title: "ఓవర్ లోడింగ్", desc: "నమోదిత సామర్థ్యం మించి ప్రయాణికులు లేదా సరుకు." },
  insurance: { title: "ఇన్సూరెన్స్ లేకుండా", desc: "చెల్లుబాటు అయ్యే థర్డ్-పార్టీ ఇన్సూరెన్స్ లేకుండా నడపడం." },
  licence: { title: "లైసెన్స్ లేకుండా", desc: "చెల్లుబాటు అయ్యే డ్రైవింగ్ లైసెన్స్ లేకుండా నడపడం." },
  racing: { title: "అనధికార రేసింగ్", desc: "ప్రభుత్వ అనుమతి లేకుండా పబ్లిక్ రోడ్డుపై రేస్." },
};

export default {
  dashboardLive: {
    subtitlePrefix: "లైవ్ రోడ్డు భద్రతా విశ్లేషణ",
    activeIncidents: "సక్రియ సంఘటనలు",
    sinceYesterday: "నిన్నటి నుండి 3 ఎక్కువ",
    issuesReported: "నివేదించిన సమస్యలు",
    today: "ఈరోజు 12",
    sosActivations: "SOS సక్రియీకరణలు",
    thisMonth: "ఈ నెల",
    resolvedIssues: "పరిష్కరించిన సమస్యలు",
    resolutionRate: "పరిష్కార రేటు",
    accidentHotspots: "ప్రమాద హాట్‌స్పాట్‌లు",
    topZones: "టాప్ 5 జోన్‌లు · గత 30 రోజులు",
    live: "లైవ్",
    recentReports: "ఇటీవలి నివేదికలు",
    liveMapView: "లైవ్ మ్యాప్",
    connectMaps: "Google Maps API ను కనెక్ట్ చేయండి",
    severity: { critical: "క్లిష్టమైన", high: "అధిక", medium: "మధ్యస్థ", low: "తక్కువ" },
    status: { pending: "పెండింగ్", verified: "ధృవీకరించబడింది", inProgress: "ప్రగతిలో", resolved: "పరిష్కరించబడింది" },
    issueTypes: { pothole: "గుంట", waterlogging: "నీటి నిలుపు", damagedRoad: "దెబ్బతిన రోడ్డు", brokenDivider: "విరిగిన డివైడర్", missingSign: "లేని సైన్" },
  },
  reportIssuePage: {
    title: "సమస్యను నివేదించండి",
    subtitle: "AI గుర్తింపు కోసం రోడ్డు చిత్రం అప్‌లోడ్ చేయండి",
    uploadTitle: "రోడ్డు చిత్రం అప్‌లోడ్",
    uploadSubtitle: "AI గుర్తింపు ప్రారంభించడానికి చిత్రాన్ని డ్రాప్ చేయండి లేదా ఎంచుకోండి.",
    issueType: "సమస్య రకం",
    severity: "తీవ్రత",
    roadLocation: "రోడ్డు / స్థానం *",
    roadPlaceholder: "ఉదా. NH-48, KM 14 మహిపాల్పూర్ దగ్గర",
    area: "ప్రాంతం",
    areaPlaceholder: "ఉదా. దక్షిణ ఢిల్లీ",
    notes: "అదనపు గమనికలు",
    notesPlaceholder: "సమస్య, కాలం, ప్రమాదం వివరించండి...",
    submit: "నివేదిక సమర్పించండి",
    submittedTitle: "నివేదిక సమర్పించబడింది",
    submittedMessage: "మీ రోడ్డు సమస్య నమోదు చేయబడింది. భారత రోడ్లను సురక్షితం చేయడంలో సహాయానికి ధన్యవాదాలు.",
    reportAnother: "మరొక నివేదిక",
    viewDashboard: "డాష్‌బోర్డ్ చూడండి",
    issueTypes: { pothole: "గుంట", damage: "దెబ్బతిన రోడ్డు", water: "నీటి నిలుపు", divider: "విరిగిన డివైడర్", sign: "లేని సైన్", other: "ఇతర" },
    severityLevels: { critical: "క్లిష్టమైన", high: "అధిక", medium: "మధ్యస్థ", low: "తక్కువ" },
    simulated: { pothole: "లోతైన గుంట ఎక్కువ నమ్మకంతో కనుగొనబడింది.", damage: "రోడ్డు పగుళ్లు కనుగొనబడ్డాయి.", water: "రోడ్డుపై నిలిచిన నీరు కనుగొనబడింది.", surface: "సాధారణ రోడ్డు అరుగు. నిర్వహణ అవసరం." },
  },
  uploader: { invalidImage: "చెల్లుబాటు అయ్యే చిత్ర ఫైల్ ఎంచుకోండి.", selected: "ఎంచుకున్నది: {{fileName}}", supportedFormats: "JPG, PNG, WEBP మదిరి ఫార్మాట్‌లు మద్దతు.", previewAlt: "రోడ్డు సమస్య ప్రివ్యూ", dropHere: "మీ చిత్రాన్ని ఇక్కడ వదలండి", chooseHint: "లేదా పరికరం నుండి ఎంచుకోండి", chooseImage: "చిత్రం ఎంచుకోండి" },
  detector: { analyzingTitle: "చిత్రం విశ్లేషణ", analyzingDescription: "AI రోడ్డు నష్ట నమూనాలను తనిఖీ చేస్తోంది.", running: "గుర్తింపు నడుస్తోంది...", failedTitle: "గుర్తింపు విఫలమైంది", emptyTitle: "ఇంకా గుర్తింపు లేదు", emptyDescription: "AI అంచనా కోసం చిత్రం అప్‌లోడ్ చేయండి.", resultTitle: "AI గుర్తింపు ఫలితం", fallbackLabel: "రోడ్డు సమస్య కనుగొనబడింది", severityLabel: "{{severity}} తీవ్రత", fallbackDescription: "చిత్రం విశ్లేషించబడి వర్గీకరించబడింది.", confidence: "నమ్మకం", fallbackType: "రోడ్డు నష్ట వర్గీకరణ", uploadedPreview: "అప్‌లోడ్ ప్రివ్యూ", uploadedAlt: "అప్‌లోడ్ చేసిన రోడ్డు సమస్య" },
  sosPage: {
    title: "అత్యవసర SOS", subtitle: "లైవ్ స్థానంతో ఒక ట్యాప్ అలర్ట్", buttonSub: "అత్యవసరం", ready: "సిస్టమ్ సిద్ధం · GPS సక్రియం", locating: "స్థానం పొందుతోంది...", dispatched: "అలర్ట్ పంపబడింది", alertSent: "అలర్ట్ పంపబడింది", servicesEta: "సేవలు తెలియజేయబడ్డాయి · ETA ~6 నిమి", reset: "రీసెట్", helper: "మీ స్థానాన్ని అత్యవసర సేవలకు పంపడానికి SOS నొక్కండి.", numbers: "అత్యవసర నంబర్లు", whatNext: "తర్వాత ఏమి జరుగుతుంది",
    contacts: { police: "పోలీసు", ambulance: "అంబులెన్స్", fire: "అగ్నిమాపక", road: "రోడ్డు హెల్ప్‌లైన్" },
    steps: { capture: "మీ GPS కోఆర్డినేట్‌లు పట్టుకోబడి పంపబడతాయి.", hospitals: "సమీప ఆసుపత్రులు గుర్తించబడతాయి.", ambulance: "అంబులెన్స్ పంపబడుతుంది.", sms: "అత్యవసర పరిచయాలకు SMS పంపబడుతుంది." },
  },
  riskPage: {
    title: "రిస్క్ అలర్ట్లు", subtitle: "మీ మార్గానికి ML ప్రమాద అంచనా", predictor: "రిస్క్ ప్రెడిక్టర్", predictorHelp: "పరిస్థితులు సెట్ చేయండి. మోడల్ స్కోర్ ఇస్తుంది.", select: "ఎంచుకోండి...", analyze: "రిస్క్ విశ్లేషణ", analyzing: "విశ్లేషిస్తోంది...", riskFactors: "రిస్క్ కారకాలు", currentScore: "ప్రస్తుత జోన్ రిస్క్ స్కోర్", feed: "లైవ్ అలర్ట్ ఫీడ్", scoreSuffix: "/100",
    labels: { critical: "క్లిష్టమైన", highRisk: "అధిక రిస్క్", moderate: "మధ్యస్థ", lowRisk: "తక్కువ రిస్క్" },
    advice: { critical: "సాధ్యమైతే ఈ జోన్ ను మానండి.", high: "అత్యంత జాగ్రత్తతో నడపండి.", medium: "సాధారణ జాగ్రత్త.", low: "జోన్ సురక్షితంగా కనిపిస్తోంది." },
    conditions: { time: "సమయం", weather: "వాతావరణం", road: "రోడ్డు పరిస్థితి", traffic: "ట్రాఫిక్" },
    options: { peakMorning: "ఉదయం పీక్ (7-10)", afternoon: "మధ్యాహ్నం", peakEvening: "సాయంత్రం పీక్ (5-9)", lateNight: "ఆలస్య రాత్రి", earlyMorning: "తెల్లవారుజాము", clear: "స్పష్టం", lightRain: "తేలికపాటి వర్షం", heavyRain: "భారీ వర్షం", fog: "పొగమంచు", denseFog: "దట్టమైన పొగమంచు", extremeHeat: "అత్యధిక వేడి", good: "మంచి", minorDamage: "చిన్న నష్టం", potholes: "గుంతలు", waterlogged: "నీరు నిలిచిన", construction: "నిర్మాణ జోన్", severelyDamaged: "తీవ్ర నష్టం", low: "తక్కువ", moderate: "మధ్యస్థ", heavy: "భారీ", stopGo: "ఆగి-ముందుకు", accidentInduced: "ప్రమాద కారణం" },
    alerts: { wetRoad: "పీక్ గంట + తడి రోడ్డు", poorVisibility: "రాత్రి + తక్కువ దృష్టి", construction: "నిర్మాణం సక్రియం", traffic: "మధ్యస్థ ట్రాఫిక్", slick: "తేలికపాటి వర్షం", visibility: "దృష్టి తగ్గింది", now: "ఇప్పుడు", minAgo: "{{count}} నిమి క్రితం" },
  },
  legalPage: {
    title: "చట్ట సమాచారం", subtitle: "భారత మోటార్ వాహన చట్టం 2019 ట్రాఫిక్ నియమాలు", prototypeTitle: "ప్రోటోటైప్ మాడ్యూల్", prototype: "ఇది స్థిర సూచన. అధికారిక మూలాలతో ధృవీకరించండి.", searchPlaceholder: "చట్టాలు, సెక్షన్లు, ట్యాగ్లు శోధన...", category: "వర్గం", quickFacts: "త్వరిత వాస్తవాలు", futureScope: "భవిష్యత్ పరిధి", futureScopeText: "GPS ఆధారంగా రాష్ట్ర/నగర నియమాలు చూపబడతాయి.", showing: "చూపిస్తోంది", ofRules: "{{count}} నియమాలలో", clearSearch: "శోధన క్లియర్", noMatch: "సరిపోలే చట్టం లేదు", firstOffence: "మొదటి అపరాధం", repeatOffence: "పునరావృత అపరాధం", imprisonment: "జైలు: {{term}}",
    categories: { all: "అన్నీ", speed: "వేగం", safety: "భద్రత", signals: "సిగ్నల్స్", driving: "డ్రైవింగ్", mobile: "మొబైల్", lane: "లేన్", overloading: "ఓవర్ లోడ్", insurance: "ఇన్సూరెన్స్", documents: "పత్రాలు", impairment: "మద్యం" },
    facts: { maxFine: "గరిష్ట జరిమానా", drunkMax: "మద్యం డ్రైవింగ్ గరిష్టం", listed: "జాబితా అపరాధాలు", actVersion: "చట్టం వెర్షన్" },
    factsValues: { maxFine: "₹20,000", drunkMax: "₹15,000+", listed: "{{count}} చట్టాలు", actVersion: "MV Act 2019" },
    lawEntries: lawEntries(lawTexts),
  },
  sosModal: {
    ariaLabel: "అత్యవసర SOS అలర్ట్", badge: "SOS", close: "మూసివేయి", seconds: "సెకన్లు", confirmIntro: "అత్యవసర SOS మీ ", liveLocation: "లైవ్ స్థానం", confirmMiddle: " తో అత్యవసర సేవలకు మరియు ", emergencyContacts: "అత్యవసర పరిచయాలకు", confirmEnd: " పంపబడుతుంది.", cancel: "రద్దు", sendNow: "ఇప్పుడు పంపు",
    stages: { confirm: "అత్యవసర అలర్ట్", locating: "మిమ్మల్ని గుర్తిస్తోంది…", sending: "పంపుతోంది…", sent: "అలర్ట్ పంపబడింది" },
    acquiringGps: "GPS సిగ్నల్ పొందుతోంది", keepOpen: "యాప్ తెరిచి ఉంచండి…", searchingSatellites: "ఉపగ్రహాలు వెతుకుతోంది", contactingServices: "అత్యవసర సేవలను సంప్రదిస్తోంది", notifyingUnits: "సమీప యూనిట్లు & పరిచయాలకు తెలియజేస్తోంది…", alertSent: "అలర్ట్ పంపబడింది", servicesNotified: "అత్యవసర సేవలకు తెలియజేయబడింది", geoNotSupported: "జియోలొకేషన్ మద్దతు లేదు.", geoFailed: "GPS యాక్సెస్ లేదు.", defaultLocation: "న్యూ ఢిల్లీ (డిఫాల్ట్)", approxLocation: "న్యూ ఢిల్లీ (అంచనా)", ambulanceEta: "అంబులెన్స్ ETA", unitDispatched: "యూనిట్ పంపబడింది", nearbyHospitals: "సమీప ఆసుపత్రులు", away: "దూరం", done: "పూర్తి", callHospital: "{{name}} కాల్",
  },
  mapUi: { yourLocation: "మీ స్థానం", noApiKey: "Google Maps API కీ లేదు.", loadFailed: "Google Maps లోడ్ విఫలమైంది.", initialising: "మ్యాప్ ప్రారంభమవుతోంది…", zoomIn: "జూమ్ ఇన్", zoomOut: "జూమ్ అవుట్", recenter: "మధ్యకు తీసుకురా", hospitals: "ఆసుపత్రులు", incidents: "సంఘటనలు", heatmap: "హీట్‌మ్యాప్", satellite: "ఉపగ్రహం", map: "మ్యాప్", you: "మీరు", reportedIssues: "నివేదించిన సమస్యలు", searchPlaceholder: "రోడ్డు, ప్రాంతం, రకం శోధన…", all: "అన్నీ", hotspotsTitle: "ప్రమాద హాట్‌స్పాట్‌లు", hotspotsSubtitle: "గత 30 రోజులు", totalIncidents: "మొత్తం సంఘటనలు", peakHour: "పీక్ గంట", trending: "పెరుగుతోంది ↑", total24h: "మొత్తం / 24గం" },
  locationErrors: { denied: "స్థాన అనుమతి నిరాకరించబడింది. GPS ప్రారంభించండి.", unavailable: "స్థానం అందుబాటులో లేదు.", timeout: "స్థాన అభ్యర్థన సమయం ముగిసింది.", unknown: "తెలియని స్థాన లోపం." },
  sos: { title: "అత్యవసర SOS", description: "అత్యవసర సమయంలో తక్షణ సహాయం", buttonLabel: "అత్యవసరానికి నొక్కండి", nearbyHospitals: "సమీప ఆసుపత్రులు", emergencyServices: "అత్యవసర సేవలు", contactingServices: "అత్యవసర సేవలను సంప్రదిస్తోంది...", locationSharing: "మీ స్థానం షేర్ అవుతోంది" },
  map: { title: "మ్యాప్ వీక్షణ", noData: "చూపించడానికి సంఘటనలు లేవు", zoomToFit: "సరిపోయేలా జూమ్", currentLocation: "ప్రస్తుత స్థానం" },
};
